# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2026-07-27 13:46:27
"""
import arcpy

def AOI052726():  # SNE_OWF_AOI

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    SNE_OWF_outlines = "SNE_OWF_outlines"

    # Process: Select (2) (Select) (analysis)
    SFW_ExportCable = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\SFW_ExportCable"
    arcpy.analysis.Select(in_features=SNE_OWF_outlines, out_feature_class=SFW_ExportCable, where_clause="COMPANY = 'South Fork Wind, LLC' And LEASE_TYPE = 'Easement'")

    # Process: Select (6) (Select) (analysis)
    VW1_ExportCable = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\VW1_ExportCable"
    arcpy.analysis.Select(in_features=SNE_OWF_outlines, out_feature_class=VW1_ExportCable, where_clause="COMPANY = 'Vineyard Wind 1 LLC' And LEASE_TYPE = 'Easement'")

    # Process: Select (5) (Select) (analysis)
    VW1 = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\VW1"
    arcpy.analysis.Select(in_features=SNE_OWF_outlines, out_feature_class=VW1, where_clause="COMPANY = 'Vineyard Wind 1 LLC' And LEASE_TYPE = 'Commercial'")

    # Process: Pairwise Buffer (4) (PairwiseBuffer) (analysis)
    VW1_Buffer = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\VW1_Buffer"
    arcpy.analysis.PairwiseBuffer(in_features=VW1, out_feature_class=VW1_Buffer, buffer_distance_or_field="10 Kilometers", dissolve_option="ALL", method="GEODESIC")

    # Process: Select (Select) (analysis)
    SFW = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\SFW"
    arcpy.analysis.Select(in_features=SNE_OWF_outlines, out_feature_class=SFW, where_clause="COMPANY = 'South Fork Wind, LLC' And LEASE_TYPE = 'Commercial'")

    # Process: Pairwise Buffer (3) (PairwiseBuffer) (analysis)
    SFW_Buffer = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\SFW_Buffer"
    arcpy.analysis.PairwiseBuffer(in_features=SFW, out_feature_class=SFW_Buffer, buffer_distance_or_field="10 Kilometers", dissolve_option="ALL", method="GEODESIC")

    # Process: Select (3) (Select) (analysis)
    RWF = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\RWF"
    arcpy.analysis.Select(in_features=SNE_OWF_outlines, out_feature_class=RWF, where_clause="COMPANY = 'Revolution Wind, LLC'")

    # Process: Pairwise Buffer (2) (PairwiseBuffer) (analysis)
    RWF_Buffer = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\RWF_Buffer"
    arcpy.analysis.PairwiseBuffer(in_features=RWF, out_feature_class=RWF_Buffer, buffer_distance_or_field="10 Kilometers", dissolve_option="ALL", method="GEODESIC")

    # Process: Select (4) (Select) (analysis)
    SRW = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\SRW"
    arcpy.analysis.Select(in_features=SNE_OWF_outlines, out_feature_class=SRW, where_clause="COMPANY = 'Sunrise Wind, LLC'")

    # Process: Pairwise Buffer (PairwiseBuffer) (analysis)
    SRW_Buffer = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\SRW_Buffer"
    arcpy.analysis.PairwiseBuffer(in_features=SRW, out_feature_class=SRW_Buffer, buffer_distance_or_field="10 Kilometers", dissolve_option="ALL", method="GEODESIC")

    # Process: Union (Union) (analysis)
    SNE_Buffers = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\SNE_Buffers"
    arcpy.analysis.Union(in_features=[[VW1_Buffer, ""], [SFW_Buffer, ""], [RWF_Buffer, ""], [SRW_Buffer, ""]], out_feature_class=SNE_Buffers)

    # Process: Dissolve (2) (Dissolve) (management)
    SNE_AOI = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\SNE_AOI"
    arcpy.management.Dissolve(in_features=SNE_Buffers, out_feature_class=SNE_AOI)

    # Process: Union (2) (Union) (analysis)
    Orsted_Buffers = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\Orsted_Buffers"
    arcpy.analysis.Union(in_features=[[SRW_Buffer, ""], [RWF_Buffer, ""], [SFW_Buffer, ""]], out_feature_class=Orsted_Buffers)

    # Process: Dissolve (Dissolve) (management)
    Orsted_AOI = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\Orsted_AOI"
    arcpy.management.Dissolve(in_features=Orsted_Buffers, out_feature_class=Orsted_AOI)

    # Process: Export Features (ExportFeatures) (conversion)
    Orsted_AOI_shp = "C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\Orsted_AOI.shp"
    arcpy.conversion.ExportFeatures(in_features=Orsted_AOI, out_features=Orsted_AOI_shp, field_mapping="Shape_Leng \"Shape_Leng\" true true false 8 Double 0 0,First,#,C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\Orsted_AOI,Shape_Leng,-1,-1;Shape_Length \"Shape_Length\" false true true 8 Double 0 0,First,#,C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\Orsted_AOI,Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false true true 8 Double 0 0,First,#,C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb\\Orsted_AOI,Shape_Area,-1,-1")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb", workspace="C:\\Users\\mmccaffrey17\\ArcGIS\\Projects\\GFW_vesselHotspots_SNE\\GFW_vesselHotspots_SNE.gdb"):
        AOI052726()
