{
  "hash": "c7acf4f89ea841df5ada7a1fc9081b51",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Spatial Analysis and Stage-to-Stage Change\"\nsubtitle: \"Hotspot structure of fishing activity across three phases of offshore wind development\"\n---\n\n## Question\n\nDoes the spatial structure of fishing activity change across the three development stages, and does it change differently for mobile and fixed gear?\n\nThe analysis runs entirely on open-source tools — `geopandas`, `libpysal`, `esda` — replacing an ArcGIS chain that could not be reproduced without a Pro licence. Every spatial input is committed to the repository; the Global Fishing Watch extracts are gitignored and regenerated by the R pull.\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code}\nimport warnings, logging\nwarnings.filterwarnings(\"ignore\")\nlogging.basicConfig(level=logging.ERROR)\n\nimport matplotlib.pyplot as plt\nimport numpy as np\nimport pandas as pd\n\nfrom gfw_fishing_osw_ais import (\n    aggregate, config as cfg, io, spatial_stats as ss, transitions as tr, viz, weights as wts\n)\n\ngrid = io.load_grid()\nowf = io.load_owf()\naoi = io.load_aoi()\npd.set_option(\"display.width\", 200)\n```\n:::\n\n\n## Methods\n\n### Spatial support\n\nThe analysis grid is 3,375 cells at 0.01°, projected to UTM 19N (EPSG:32619), covering the Ørsted AOI. Records are joined to cells with `geopandas.sjoin` and rolled up per cell per stage:\n\n$$\\text{MonthMean}_i = \\frac{\\sum_j h_{ij}}{M_s}$$\n\nwhere $h_{ij}$ are hours in cell $i$ and $M_s$ is the number of months in stage $s$ (44 / 43 / 40). The denominator is the *stage* length, not the number of months that cell was active, so zero-inflation is structural.\n\nStatistics run on $\\sqrt{\\text{MonthMean}}$, chosen on the evidence in `01-data-exploration.qmd`.\n\n### Spatial weights\n\n::: {.callout-warning}\n## Geometric contiguity is unusable on this grid\nThe grid was built by drawing an independent 0.01° square around each GFW point and reprojecting with `PRESERVE_SHAPE`, so adjacent cells do not share exact vertices. `Queen.from_dataframe` returns **1.96 mean neighbours across 74 disconnected components**, which would render every local statistic meaningless.\n:::\n\nContiguity is instead derived analytically from the lattice indices the shapefile already carries. Two cells are Queen neighbours iff their integer indices differ by at most one on each axis — no geometry predicate, no tolerance.\n\n::: {#tbl-weights .cell tbl-cap='Neighbour-count distribution of the lattice-derived Queen weights' execution_count=2}\n``` {.python .cell-code}\nw = wts.lattice_queen(grid)\nw_star = wts.gi_star_weights(grid)\nwts.validate_weights(w)\nwts.neighbor_summary(w)\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>n_neighbors</th>\n      <th>n_cells</th>\n      <th>pct_cells</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>4</td>\n      <td>43</td>\n      <td>1.3</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>5</td>\n      <td>128</td>\n      <td>3.8</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>6</td>\n      <td>35</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>7</td>\n      <td>62</td>\n      <td>1.8</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>8</td>\n      <td>3107</td>\n      <td>92.1</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#weights-summary .cell execution_count=3}\n``` {.python .cell-code}\nprint(f\"n = {w.n}, mean neighbours = {w.mean_neighbors:.2f}, \"\n      f\"components = {w.n_components}, islands = {len(w.islands)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nn = 3375, mean neighbours = 7.80, components = 1, islands = 0\n```\n:::\n:::\n\n\nValidated three ways: `validate_weights` rejects the geometric construction it guards against; all 26,312 neighbour pairs lie within one cell diagonal (max 1,395 m against a legal 1,424 m), so no false links are created; and the relation is perfectly symmetric.\n\n### Statistics\n\n| Purpose | Method | Inference |\n|---|---|---|\n| Global clustering | `esda.Moran` | analytic |\n| Global high/low | `esda.G` | analytic |\n| Local hotspots (Gi\\*) | `esda.G_Local`, **binary weights** | analytic, BH-FDR |\n| Local clusters/outliers | `esda.Moran_Local`, 999 permutations, seeded | conditional randomisation, BH-FDR |\n\nTwo points of care, both documented in `00b-plan-revisions.qmd`:\n\n**Gi\\* requires binary weights.** Its variance depends on the weight sum $W_i$; row standardisation forces $W_i = 1$ and compresses every z-score. On these data that is the difference between max |z| of 10.78 and 3.96 — between 832 significant cells and none. `esda.G_Local` defaults to `transform=\"R\"` and re-standardises in place, so the call site passes `transform=\"B\"`.\n\n**Permutations are seeded** (`cfg.RANDOM_SEED = 42`). The archived workflow set no seed and its Local Moran's results were therefore not reproducible.\n\n::: {#run-analysis .cell execution_count=4}\n``` {.python .cell-code}\ncells_afe, glob_afe = ss.run_all(\"afe\")\ncells_vp, glob_vp = ss.run_all(\"vp\")\ntrans_afe = tr.run_transitions(\"afe\", cells_afe, grid)\ntrans_vp = tr.run_transitions(\"vp\", cells_vp, grid)\n```\n:::\n\n\n\n\n## Global spatial autocorrelation\n\n::: {#tbl-global .cell tbl-cap='Global Moran\\'s I on the sqrt surfaces, all gear' execution_count=6}\n``` {.python .cell-code}\ng = pd.concat([glob_vp, glob_afe]).query(\"gear_class == 'ALL'\")\ng[[\"dataset\", \"stage\", \"n_active\", \"morans_i\", \"morans_z\", \"morans_p\",\n   \"general_g_z\", \"n_hot\", \"n_cold\"]]\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>dataset</th>\n      <th>stage</th>\n      <th>n_active</th>\n      <th>morans_i</th>\n      <th>morans_z</th>\n      <th>morans_p</th>\n      <th>general_g_z</th>\n      <th>n_hot</th>\n      <th>n_cold</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>vp</td>\n      <td>1</td>\n      <td>3163</td>\n      <td>0.699875</td>\n      <td>79.978629</td>\n      <td>0.0</td>\n      <td>71.843727</td>\n      <td>599</td>\n      <td>480</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>vp</td>\n      <td>2</td>\n      <td>3214</td>\n      <td>0.719148</td>\n      <td>82.180173</td>\n      <td>0.0</td>\n      <td>73.875774</td>\n      <td>619</td>\n      <td>537</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>vp</td>\n      <td>3</td>\n      <td>3247</td>\n      <td>0.716428</td>\n      <td>81.869520</td>\n      <td>0.0</td>\n      <td>73.266896</td>\n      <td>739</td>\n      <td>637</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>afe</td>\n      <td>1</td>\n      <td>1530</td>\n      <td>0.346873</td>\n      <td>39.656226</td>\n      <td>0.0</td>\n      <td>39.788614</td>\n      <td>367</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>afe</td>\n      <td>2</td>\n      <td>1451</td>\n      <td>0.415843</td>\n      <td>47.534517</td>\n      <td>0.0</td>\n      <td>47.735596</td>\n      <td>338</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>afe</td>\n      <td>3</td>\n      <td>1738</td>\n      <td>0.494598</td>\n      <td>56.530386</td>\n      <td>0.0</td>\n      <td>55.866877</td>\n      <td>397</td>\n      <td>0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nVessel presence is strongly clustered and near-constant across stages. **Apparent fishing effort clusters progressively more strongly** — 0\\.347 → 0\\.416 → 0\\.495 — meaning fishing effort concentrates spatially as development proceeds, even as total mobile-gear effort returns to baseline.\n\n::: {#cell-fig-moran .cell execution_count=7}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(7, 4))\nfor ds, glob, color in ((\"vp\", glob_vp, \"#2166ac\"), (\"afe\", glob_afe, \"#b2182b\")):\n    sub = glob.query(\"gear_class == 'ALL'\").sort_values(\"stage\")\n    ax.plot([cfg.STAGES[s].label for s in sub.stage], sub.morans_i,\n            \"o-\", color=color, linewidth=2, markersize=8, label=cfg.DATASETS[ds].label)\nax.set_ylabel(\"Global Moran's I\")\nax.set_ylim(0, 0.8)\nax.legend(frameon=False)\nax.spines[[\"top\", \"right\"]].set_visible(False)\nplt.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![Global Moran's I by stage. Fishing effort concentrates; vessel presence does not.](02-spatial-analysis_files/figure-html/fig-moran-output-1.png){#fig-moran width=1101 height=624}\n:::\n:::\n\n\n## Hotspot structure by stage\n\n::: {#cell-fig-gi-afe .cell execution_count=8}\n``` {.python .cell-code}\nfig = viz.reference_strip(\"afe\", cells_afe, grid, owf, aoi)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Getis-Ord Gi* hotspots, apparent fishing effort, by development stage. Ørsted lease areas outlined.](02-spatial-analysis_files/figure-html/fig-gi-afe-output-1.png){#fig-gi-afe width=1773 height=736}\n:::\n:::\n\n\n## Stage-to-stage change\n\nThree maps read side by side ask a viewer to hold one in working memory while scanning the next. The change maps do that differencing explicitly.\n\n::: {#cell-fig-hero-afe .cell execution_count=9}\n``` {.python .cell-code}\nfig = viz.hero_figure(\"afe\", trans_afe, grid, owf, aoi)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Change in apparent-fishing-effort hotspot structure across both stage transitions.](02-spatial-analysis_files/figure-html/fig-hero-afe-output-1.png){#fig-hero-afe width=1906 height=1170}\n:::\n:::\n\n\n::: {#tbl-change-afe .cell tbl-cap='Stage 2 to Stage 3 change in hotspot classification, all gear' execution_count=10}\n``` {.python .cell-code}\ntrans_afe[(2, 3, None)][\"summary\"]\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>change</th>\n      <th>n_cells</th>\n      <th>area_km2</th>\n      <th>pct_grid</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>stable hot</td>\n      <td>185</td>\n      <td>172.7</td>\n      <td>5.5</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>gained hot</td>\n      <td>212</td>\n      <td>197.9</td>\n      <td>6.3</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>lost hot</td>\n      <td>153</td>\n      <td>142.8</td>\n      <td>4.5</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>hot to cold</td>\n      <td>0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>cold to hot</td>\n      <td>0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>stable cold</td>\n      <td>0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>gained cold</td>\n      <td>0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>lost cold</td>\n      <td>0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>no change</td>\n      <td>2825</td>\n      <td>2636.1</td>\n      <td>83.7</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#tbl-matrix .cell tbl-cap='Condensed Gi* transition matrix, Stage 2 to Stage 3, apparent fishing effort' execution_count=11}\n``` {.python .cell-code}\ntrans_afe[(2, 3, None)][\"matrix_condensed\"]\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>to</th>\n      <th>hot</th>\n      <th>ns</th>\n      <th>cold</th>\n    </tr>\n    <tr>\n      <th>from</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>hot</th>\n      <td>185</td>\n      <td>153</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>ns</th>\n      <td>212</td>\n      <td>2825</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>cold</th>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.callout-note}\n## What these tables do and do not say\nEach surface is FDR-corrected within its own stage, and the transition tables describe how those classifications moved. There is **no statistical test of the difference between two Gi\\* surfaces**. Read them as description, not as a significance test of change.\n:::\n\n## The gear comparison\n\n::: {#cell-fig-gear-afe .cell execution_count=12}\n``` {.python .cell-code}\nfig = viz.gear_small_multiples(\"afe\", trans_afe, grid, owf, aoi)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Stage 2 to Stage 3 change by gear class. Mobile contracts slightly; fixed expands substantially.](02-spatial-analysis_files/figure-html/fig-gear-afe-output-1.png){#fig-gear-afe width=1801 height=782}\n:::\n:::\n\n\n::: {#tbl-gear-change .cell tbl-cap='Net hotspot area change, Stage 2 to Stage 3, by gear class' execution_count=13}\n``` {.python .cell-code}\nrows = []\nfor gc in (None,) + cfg.ANALYSIS_GEAR_CLASSES:\n    key = (2, 3, gc)\n    if key not in trans_afe:\n        continue\n    s = trans_afe[key][\"summary\"].set_index(\"change\")\n    rows.append({\n        \"gear_class\": gc or \"ALL\",\n        \"gained hot km2\": s.loc[\"gained hot\", \"area_km2\"],\n        \"lost hot km2\": s.loc[\"lost hot\", \"area_km2\"],\n        \"net km2\": round(s.loc[\"gained hot\", \"area_km2\"] - s.loc[\"lost hot\", \"area_km2\"], 1),\n    })\npd.DataFrame(rows)\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>gear_class</th>\n      <th>gained hot km2</th>\n      <th>lost hot km2</th>\n      <th>net km2</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>ALL</td>\n      <td>197.9</td>\n      <td>142.8</td>\n      <td>55.1</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>MOBILE</td>\n      <td>138.2</td>\n      <td>147.4</td>\n      <td>-9.2</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>FIXED</td>\n      <td>194.6</td>\n      <td>54.1</td>\n      <td>140.5</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>UNRESOLVED</td>\n      <td>258.0</td>\n      <td>67.1</td>\n      <td>190.9</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#tbl-gear-rates .cell tbl-cap='Effort intensity by gear class and stage' execution_count=14}\n``` {.python .cell-code}\ntr.stage_rates(\"afe\").query(\"gear_class in ['MOBILE', 'FIXED', 'POLE_AND_LINE']\")\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>dataset</th>\n      <th>stage</th>\n      <th>stage_label</th>\n      <th>gear_class</th>\n      <th>months</th>\n      <th>hours</th>\n      <th>vessels_mmsi</th>\n      <th>hours_per_month</th>\n      <th>hours_per_vessel_month</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>afe</td>\n      <td>1</td>\n      <td>Stage 1</td>\n      <td>MOBILE</td>\n      <td>44</td>\n      <td>4721.7</td>\n      <td>84</td>\n      <td>107.31</td>\n      <td>1.2775</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>afe</td>\n      <td>1</td>\n      <td>Stage 1</td>\n      <td>FIXED</td>\n      <td>44</td>\n      <td>453.8</td>\n      <td>10</td>\n      <td>10.31</td>\n      <td>1.0313</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>afe</td>\n      <td>1</td>\n      <td>Stage 1</td>\n      <td>POLE_AND_LINE</td>\n      <td>44</td>\n      <td>144.0</td>\n      <td>13</td>\n      <td>3.27</td>\n      <td>0.2517</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>afe</td>\n      <td>2</td>\n      <td>Stage 2</td>\n      <td>MOBILE</td>\n      <td>43</td>\n      <td>5894.4</td>\n      <td>88</td>\n      <td>137.08</td>\n      <td>1.5577</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>afe</td>\n      <td>2</td>\n      <td>Stage 2</td>\n      <td>FIXED</td>\n      <td>43</td>\n      <td>559.3</td>\n      <td>15</td>\n      <td>13.01</td>\n      <td>0.8672</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>afe</td>\n      <td>2</td>\n      <td>Stage 2</td>\n      <td>POLE_AND_LINE</td>\n      <td>43</td>\n      <td>264.1</td>\n      <td>18</td>\n      <td>6.14</td>\n      <td>0.3412</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>afe</td>\n      <td>3</td>\n      <td>Stage 3</td>\n      <td>MOBILE</td>\n      <td>40</td>\n      <td>4272.3</td>\n      <td>89</td>\n      <td>106.81</td>\n      <td>1.2001</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>afe</td>\n      <td>3</td>\n      <td>Stage 3</td>\n      <td>FIXED</td>\n      <td>40</td>\n      <td>1775.9</td>\n      <td>25</td>\n      <td>44.40</td>\n      <td>1.7759</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>afe</td>\n      <td>3</td>\n      <td>Stage 3</td>\n      <td>POLE_AND_LINE</td>\n      <td>40</td>\n      <td>364.8</td>\n      <td>30</td>\n      <td>9.12</td>\n      <td>0.3040</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Result\n\n**Mobile-gear hotspot area is flat to slightly contracting; fixed-gear hotspot area expands substantially.** Mobile effort rises into Stage 2 then returns to within 1% of its Stage 1 baseline (107\\.3 → 137\\.1 → 106\\.8 hours per month), while fixed gear climbs 4\\.3× (10\\.3 → 13\\.0 → 44\\.4) on both a larger fleet and higher per-vessel intensity.\n\nSpatially, mobile-gear hotspots sit on the western margin of the AOI, largely outside the lease areas. Fixed-gear hotspots expand around and into the lease perimeter.\n\n## Activity inside the lease areas\n\nThe hotspot maps show where activity concentrates. This asks the blunter question of whether it happens inside the lease footprints at all.\n\n::: {#tbl-lease-afe .cell tbl-cap='Apparent fishing effort inside the lease polygons versus elsewhere in the AOI' execution_count=15}\n``` {.python .cell-code}\nlease_afe = tr.lease_share(\"afe\")\nlease_afe.query(\"gear_class in ['ALL', 'MOBILE', 'FIXED']\")\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>dataset</th>\n      <th>stage</th>\n      <th>stage_label</th>\n      <th>gear_class</th>\n      <th>in_lease_hours_per_month</th>\n      <th>outside_hours_per_month</th>\n      <th>pct_in_lease</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>afe</td>\n      <td>1</td>\n      <td>Stage 1</td>\n      <td>ALL</td>\n      <td>39.5</td>\n      <td>108.0</td>\n      <td>26.8</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>afe</td>\n      <td>1</td>\n      <td>Stage 1</td>\n      <td>MOBILE</td>\n      <td>30.8</td>\n      <td>76.5</td>\n      <td>28.7</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>afe</td>\n      <td>1</td>\n      <td>Stage 1</td>\n      <td>FIXED</td>\n      <td>0.8</td>\n      <td>9.5</td>\n      <td>8.2</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>afe</td>\n      <td>2</td>\n      <td>Stage 2</td>\n      <td>ALL</td>\n      <td>35.7</td>\n      <td>150.6</td>\n      <td>19.1</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>afe</td>\n      <td>2</td>\n      <td>Stage 2</td>\n      <td>MOBILE</td>\n      <td>25.9</td>\n      <td>111.2</td>\n      <td>18.9</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>afe</td>\n      <td>2</td>\n      <td>Stage 2</td>\n      <td>FIXED</td>\n      <td>1.6</td>\n      <td>11.4</td>\n      <td>12.1</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>afe</td>\n      <td>3</td>\n      <td>Stage 3</td>\n      <td>ALL</td>\n      <td>33.6</td>\n      <td>196.8</td>\n      <td>14.6</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>afe</td>\n      <td>3</td>\n      <td>Stage 3</td>\n      <td>MOBILE</td>\n      <td>17.6</td>\n      <td>89.2</td>\n      <td>16.5</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>afe</td>\n      <td>3</td>\n      <td>Stage 3</td>\n      <td>FIXED</td>\n      <td>3.6</td>\n      <td>40.8</td>\n      <td>8.1</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#tbl-lease-vp .cell tbl-cap='Vessel presence inside the lease polygons versus elsewhere in the AOI' execution_count=16}\n``` {.python .cell-code}\ntr.lease_share(\"vp\").query(\"gear_class in ['ALL', 'MOBILE', 'FIXED']\")\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>dataset</th>\n      <th>stage</th>\n      <th>stage_label</th>\n      <th>gear_class</th>\n      <th>in_lease_hours_per_month</th>\n      <th>outside_hours_per_month</th>\n      <th>pct_in_lease</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>vp</td>\n      <td>1</td>\n      <td>Stage 1</td>\n      <td>ALL</td>\n      <td>96.5</td>\n      <td>451.5</td>\n      <td>17.6</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>vp</td>\n      <td>1</td>\n      <td>Stage 1</td>\n      <td>MOBILE</td>\n      <td>51.4</td>\n      <td>239.4</td>\n      <td>17.7</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>vp</td>\n      <td>1</td>\n      <td>Stage 1</td>\n      <td>FIXED</td>\n      <td>7.0</td>\n      <td>29.7</td>\n      <td>19.1</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>vp</td>\n      <td>2</td>\n      <td>Stage 2</td>\n      <td>ALL</td>\n      <td>101.0</td>\n      <td>565.7</td>\n      <td>15.1</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>vp</td>\n      <td>2</td>\n      <td>Stage 2</td>\n      <td>MOBILE</td>\n      <td>43.4</td>\n      <td>294.2</td>\n      <td>12.9</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>vp</td>\n      <td>2</td>\n      <td>Stage 2</td>\n      <td>FIXED</td>\n      <td>9.7</td>\n      <td>44.0</td>\n      <td>18.0</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>vp</td>\n      <td>3</td>\n      <td>Stage 3</td>\n      <td>ALL</td>\n      <td>123.3</td>\n      <td>664.5</td>\n      <td>15.6</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>vp</td>\n      <td>3</td>\n      <td>Stage 3</td>\n      <td>MOBILE</td>\n      <td>40.0</td>\n      <td>273.3</td>\n      <td>12.8</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>vp</td>\n      <td>3</td>\n      <td>Stage 3</td>\n      <td>FIXED</td>\n      <td>16.2</td>\n      <td>117.0</td>\n      <td>12.2</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-fig-lease .cell execution_count=17}\n``` {.python .cell-code}\nsub = lease_afe.query(\"gear_class == 'ALL'\").sort_values(\"stage\")\nx = np.arange(len(sub))\nfig, ax = plt.subplots(figsize=(7.5, 4))\nax.bar(x - 0.19, sub.in_lease_hours_per_month, 0.38, label=\"Inside lease areas\", color=\"#b2182b\")\nax.bar(x + 0.19, sub.outside_hours_per_month, 0.38, label=\"Elsewhere in AOI\", color=\"#bbbbbb\")\nax.set_xticks(x, sub.stage_label)\nax.set_ylabel(\"Apparent fishing hours per month\")\nax.legend(frameon=False)\nax.spines[[\"top\", \"right\"]].set_visible(False)\nplt.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![Apparent fishing effort inside versus outside the lease areas. Effort inside is flat; growth happens entirely outside.](02-spatial-analysis_files/figure-html/fig-lease-output-1.png){#fig-lease width=1184 height=624}\n:::\n:::\n\n\n## Synthesis {#sec-synthesis}\n\n### The aggregate increase is mostly not real\n\nApparent fishing effort rises 147\\.5 → 186\\.2 → 230\\.4 hours per month across stages. But the tracked fleet grows 152 → 178 → 216 vessels, and **effort per vessel-month is essentially flat at 0\\.97 → 1\\.05 → 1\\.07**. Nearly all of the headline increase is AIS coverage expanding, not fishing intensifying. Vessel presence behaves the same way (0\\.82 → 0\\.88 → 0\\.94).\n\nThis is the most important framing constraint in the analysis. Any statement of the form \"fishing effort increased during construction\" is, on these data, largely a statement about AIS adoption.\n\n### The real signal is gear divergence, and it replicates\n\n| hours per vessel-month | Stage 1 | Stage 2 | Stage 3 |\n|---|---:|---:|---:|\n| Mobile — effort | 1\\.28 | 1\\.56 | **1\\.20** |\n| Fixed — effort | 1\\.03 | 0\\.87 | **1\\.78** |\n| Mobile — presence | 1\\.05 | 1\\.12 | **1\\.02** |\n| Fixed — presence | 0\\.92 | 1\\.19 | **2\\.18** |\n\nFixed gear intensifies per vessel in **both independent measures** while mobile returns to baseline in both. Fixed-gear effort grows 4\\.3× in absolute terms on a fleet that only grew from 10 to 25 vessels. Coverage growth would lift both gear types equally, so this is a behavioural difference rather than a sampling artifact.\n\n### The fishery grew around the leases, not inside them\n\nEffort inside the lease footprints is **flat in absolute terms** — 39\\.5 → 35\\.7 → 33\\.6 hours per month — while effort elsewhere in the AOI nearly doubles, 108\\.0 → 150\\.6 → 196\\.8. The in-lease share therefore falls from 26\\.8% to 14\\.6%.\n\nThat distinction matters: this is relative displacement, not absolute abandonment. Mobile gear shows the clearest withdrawal, its in-lease share falling 28\\.7% → 18\\.9% → 16\\.5%.\n\nVessel presence does the opposite. Presence inside the leases *rises* (96.5 → 102.9 → 128.0 hours per month) on a roughly constant share. **Vessels increasingly move through the lease areas without fishing in them.**\n\nStructurally, Global Moran's I for effort climbs 0\\.347 → 0\\.416 → 0\\.495 — activity concentrates into a consolidated band along the western AOI margin. Net hotspot area change from Stage 2 to Stage 3 is −9\\.2 km² for mobile against \\+140\\.5 km² for fixed.\n\n## Caveats on the interpretation\n\n**This is not a causal design.** There is no control area and no before-after-control-impact structure. Displacement, shifting stock distribution, regulatory change and fuel prices are not separable here. The analysis describes what changed in this AOI over this period; it does not attribute that change to wind development.\n\n**Apparent fishing effort is a model output**, not observed fishing. GFW infers it from vessel behaviour, and the inference itself may perform differently around construction activity.\n\n**The unresolved class expands most of all** (\\+190\\.9 km² net, 258\\.0 gained against 67\\.1 lost) and is not interpretable as a gear signal — it reflects GFW registry coverage. Some genuine mobile and fixed activity sits in that panel. It is shown rather than hidden for exactly that reason.\n\n**Eleven offshore-wind charter and research vessels were removed** beyond the 35 on Ørsted's own list, after they were found driving an apparent fishing-effort increase inside the Revolution Wind lease. Eight were identified by a behavioural screen rather than confirmed by registry evidence. Before that correction the analysis showed mobile effort flat and a 448 km² cold-spot region that does not exist. The screen also cannot detect an established fishing vessel that takes a charter — the *Virginia Wave* escaped the first pass for exactly that reason. Full detail in `00b-plan-revisions.qmd`.\n\n**AIS coverage grows across the study period**, so absolute hours are not comparable between stages without the per-vessel normalisation reported above.\n\n**The transition tables describe, they do not test.** Each surface is FDR-corrected within its own stage; there is no significance test of the difference between two surfaces.\n\n**Local Moran's `LL` counts are unreliable for sparse gear classes**, where they are dominated by the structural zero field rather than by meaningful low-activity clusters. Gi\\* is the more trustworthy statistic on those surfaces — it reports no cold spots there, correctly, since a cell cannot sit significantly below a floor of zero.\n\n## Why this matters\n\n**Fisheries displacement is the central socioeconomic question in US offshore wind permitting, and it is chronically evidence-poor.** Federal decisions and the compensation frameworks in Rhode Island and Massachusetts rest largely on stated-preference surveys and self-reported vessel trip reports. This provides an independent, spatially explicit, reproducible measure built from a public data source.\n\n**The gear-specific result has direct management implications.** Mobile and fixed gear are not interchangeable in mitigation design — turbine spacing, cable burial and transit corridors affect a trawler and a pot boat differently. Evidence that fixed-gear activity intensified while mobile withdrew argues against uniform mitigation, and speaks to which fleet segments bear the cost.\n\n**The charter-vessel finding generalises well beyond this project.** Offshore wind developers charter commercial fishing hulls as scout and safety vessels. Those vessels retain their fishing registry classification, so GFW records their project work as apparent fishing effort — concentrated inside the lease areas, precisely during construction. Any GFW-based study of fishing activity around offshore wind is exposed to this, and the bias runs toward finding *increased* fishing exactly where and when one would look for displacement. Filtering on vessel name, as is common, does not remove it: one hull emits several name strings.\n\n**It establishes a reproducible baseline.** Sunrise Wind remains under construction and further Southern New England projects are permitted. This pipeline runs from committed inputs with no proprietary software, so the same analysis re-runs against future data as those projects progress.\n\n## Reproducibility\n\n::: {#provenance .cell execution_count=18}\n``` {.python .cell-code}\nimport esda, geopandas, libpysal, scipy\nprint(f\"geopandas {geopandas.__version__}   libpysal {libpysal.__version__}\")\nprint(f\"esda {esda.__version__}        scipy {scipy.__version__}\")\nprint(f\"seed {cfg.RANDOM_SEED}   permutations {cfg.N_PERMUTATIONS}   FDR alpha {cfg.FDR_ALPHA}\")\nprint(f\"month denominator: {cfg.MONTH_DENOMINATOR}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ngeopandas 1.1.4   libpysal 4.15.0\nesda 2.10.0        scipy 1.18.1\nseed 42   permutations 999   FDR alpha 0.05\nmonth denominator: nominal\n```\n:::\n:::\n\n\nExact package versions are pinned in `uv.lock`. Re-running this document reproduces every figure and table bit-for-bit; the Local Moran's permutations are seeded.\n\n",
    "supporting": [
      "02-spatial-analysis_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}